name: Update and Clean TPER GTFS

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  download_and_clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: pip install requests beautifulsoup4

      - name: Download latest GTFS feeds
        run: python download_gtfs.py

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Clone and build gtfstidy
        run: |
          git clone https://github.com/patrickbr/gtfstidy.git
          cd gtfstidy
          make build

      - name: Add gtfstidy to PATH
        run: echo "${{ github.workspace }}/gtfstidy" >> $GITHUB_PATH

      - name: Run gtfstidy to clean and merge feeds
        run: |
          export PATH=$PATH:$HOME/go/bin
          gtfstidy -SCRmcdsOeD gtfs_*_latest.zip --merge -o gtfs_tper_clean.zip > tidy.log


      - name: Commit and push cleaned feed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f gtfs_*_latest.zip gtfs_tper_clean.zip tidy.log
          git commit -m "Update and clean merged GTFS feed" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

